# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjtcaAIX4sMDWLrtxc_C5uu79BIgUy1W
"""

#!pip install streamlit
#!pip install PyPDF4
#!pip install nltk

import streamlit as st
import PyPDF4
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize


# Function to extract text from PDF
def extract_text(uploaded_file):
    text = ""
    reader = PyPDF4.PdfFileReader(uploaded_file)
    for page_num in range(reader.numPages):
        page = reader.getPage(page_num)
        text += page.extractText()
    return text

# Function to answer user questions
def answer_question(question, text):
    # Implement your question answering logic here
    sentences = sent_tokenize(text)
    matching_sentences = [sentence for sentence in sentences if question.lower() in sentence.lower()]
    if matching_sentences:
        return matching_sentences[0]  # Return the first matching sentence as the answer
    else:
        return "Sorry, I couldn't find an answer to your question."

# Streamlit app
def main():
    st.title("PDF-Inquiry-Guide")

    # File uploader
    uploaded_file = st.file_uploader("Upload a PDF", type=["pdf"])

    if uploaded_file is not None:
        text = extract_text(uploaded_file)
        st.write("### Ask your PDF:")
        
        question_input_key = 0  # Initialize key counter
        while True:
            # Ask a question
            question = st.text_input("You: Ask your question", key=f"question_input_{question_input_key}")
            
            if question:
                # Answer the question
                answer = answer_question(question, text)
                st.write("ChatPDF: " + answer)
                question_input_key += 1  # Increment key counter
            else:
                break

if __name__ == "__main__":
    main()

